# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_info', models.CharField(max_length=500, verbose_name='商品简介信息')),
                ('goods_pic', models.CharField(max_length=5000, verbose_name='展示界面的商品图标位置,多个图片位置以;分割')),
                ('goods_url', models.CharField(max_length=300, verbose_name='商品详情位置')),
                ('shoppingcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.ShoppingCart')),
            ],
        ),
    ]
